### ISSUE TITLE
clean up globus endpoints 

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-service#86]
we need to routinely clean up globus endpoints that are no longer required - submission complete.

**Comment by jdhayhurst** [comment]
Investigate possibility of recreate endpoints - if this is achievable implement the delete endpoint call after successful submission. If we need to enable users to reuse that endpoint then we can reinstate the endpoint.

**Comment by jdhayhurst** [comment]
It is not possible to recreate a deleted endpoint, but one can create a new endpoint using the same directory as before. The globus directory will therefore be the same but the origin id will be different as this is generated by globus each time an endpoint is created. This origin ID is needed to actually point the user to the new link, so we could share this with the user if necessary.

**Comment by jdhayhurst** [comment]
globus endpoints should be closed when:
1) submissions expire
2) submissions have successfully validated and files have gone to staging

**Comment by jdhayhurst** [comment]
tested and working. In the event of the file not being available to move the endpoint will not be deactivated, which is good. However, an inelegant error is raised instead:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sumstats_service/sumstats_service/resources/api_utils.py", line 279, in publish_and_clean_sumstats
    if study.move_file_to_staging() is True:
  File "/sumstats_service/sumstats_service/resources/study_service.py", line 225, in move_file_to_staging
    return ssf.move_file_to_staging()
  File "/sumstats_service/sumstats_service/resources/file_handler.py", line 283, in move_file_to_staging
    dest_file = os.path.join(dest_dir, self.staging_file_name + ext)
TypeError: must be str, not NoneType
```
We should catch this more cleanly

**Comment by jdhayhurst** [comment]
test in a multi-study case
